// This is some example data to use.
// Feel free to modify this to make sense with the game system you're using.
var dynamic_sheet_attrs = {
  "name" : "Ashley Chrissel",
  "class" : "necromancer",
  "race" : "human",
  "level" : "1",

  "avatar_image" : "https://db4sgowjqfwig.cloudfront.net/images/3034357/human_cleric_by_njoo.jpg",

  "str" : "11",
  "str_modifier" : "0",
  "str_modifier_plus_level" : "1",
  "con" : "8",
  "con_modifier" : "-1",
  "con_modifier_plus_level" : "0",
  "dex" : "14",
  "dex_modifier" : "+2",
  "dex_modifier_plus_level" : "+3",
  "int" : "17",
  "int_modifier" : "+3",
  "int_modifier_plus_level" : "+4",
  "wis" : "12",
  "wis_modifier" : "+1",
  "wis_modifier_plus_level" : "+2",
  "cha" : "15",
  "cha_modifier" : "+2",
  "cha_modifier_plus_level" : "+3",

  "initiative" : "+3",
  "ac" : "12",
  "pd" : "11",
  "md" : "14",

  "current_hp" : "18",
  "max_hp" : "18",
  "current_recoveries" : "8",
  "max_recoveries" : "8",
  "recovery_roll" : "1d6-1",

  "melee_attack1" : "+1",
  "melee_attack2" : "",
  "melee_attack3" : "",
  "ranged_attack1" : "-1",
  "ranged_attack2" : "",
  "ranged_attack3" : "",

  "melee_hit1" : "1d4+1",
  "melee_hit2" : "",
  "melee_hit3" : "",
  "ranged_hit1" : "1d4-1",
  "ranged_hit2" : "",
  "ranged_hit3" : "",

  "melee_miss1" : "1",
  "melee_miss2" : "",
  "melee_miss3" : "",
  "ranged_miss1" : "0",
  "ranged_miss2" : "",
  "ranged_miss3" : "",

  "one_unique_thing" : "The Lich King spared my life by turning me into a phylactery and now I must eat magic to survive.",

  "icon_relationship1" : "±2 The Lich King",
  "icon_relationship2" : "+1 The Dwarf King",
  "icon_relationship3" : "",
  "icon_relationship4" : "",

  "melee1_attack" : "+1",
  "melee1_hit" : "1d4",
  "melee1_miss" : "1",
  "melee2_attack" : "-1",
  "melee2_hit" : "1d6",
  "melee2_miss" : "1",
  "melee3_attack" : "-2",
  "melee3_hit" : "1d8",
  "melee3_miss" : "1",

  "background1" : "+3 youngest daughter of the Manor of Frozen Light",
  "background2" : "+3 relic-hunter for hire",
  "background3" : "+2 silver-tongued troublemaker",
  "background4" : "",
  "background5" : "",
  "background6" : "",

  "racial_power" : "roll initiative twice and keep one",

  "talent1" : "Deathknell",
  "talent2" : "Skeletal Minion",
  "talent3" : "Sorta Dead",
  "talent4" : "",
  "talent5" : "",

  "class_feature01" : "Arcane Implements",
  "class_feature02" : "Death's Master",
  "class_feature03" : "Ritual Magic",
  "class_feature04" : "Spell Choices",
  "class_feature05" : "Summoning",
  "class_feature06" : "Wasting Away",
  "class_feature07" : "",
  "class_feature08" : "",
  "class_feature09" : "",
  "class_feature10" : "",

  "feat01" : "Wasting Away (Adventurer)",
  "feat02" : "Skeletal Minion (Adventurer)",
  "feat03" : "",
  "feat04" : "",
  "feat05" : "",
  "feat06" : "",
  "feat07" : "",
  "feat08" : "",
  "feat09" : "",
  "feat10" : "",
  "feat11" : "",

  "magic_item1" : "",

  "item1" : "dagger",
  "item2" : "",
  "item3" : "",
  "item4" : "",
  "item5" : "",
  "item6" : "",

  "incremental_ability_score_bonus" : "0",
  "incremental_icon_relationship" : "0",
  "incremental_extra_magic_item" : "0",
  "incremental_feat" : "1",
  "incremental_hit_points" : "0",
  "incremental_skills" : "0",
  "incremental_power1" : "1",
  "incremental_power2" : "0",
  "incremental_power3" : "0",
  "incremental_power4" : "0",

  "player" : "<a href='http://www.obsidianportal.com/profile/Yithian'>Yithian</a>",
  "campaign" : "<a href='http://tilting-at-windmills.obsidianportal.com'>Tilting at Windmills</a>",
};
