// This is some example data to use.
// Feel free to modify this to make sense with the game system you're using.
var dynamic_sheet_attrs = {
  "name" : "Fyor Kast",
  "species" : "Nautolan",
  "career" : "Guardian",
  "specializations" : "Protector",

  "avatar_image" : "https://db4sgowjqfwig.cloudfront.net/images/3698621/10-king-mannix_square_thumb.jpg",

  "soak_w" : "5",
  "wound" : "17",
  "wound_current" : "1",
  "strain" : "11",
  "strain_current" : "0",
  "ranged_def" : "0",
  "melee_def" : "0",

  "brawn" : "4",
  "agility" : "2",
  "intellect" : "3",
  "cunning" : "2",
  "willpower" : "2",
  "presence" : "2",

  "astrogation_career" : "0",
  "astrogation" : "0",
  "athletics_career" : "1",
  "athletics" : "1",
  "charm_career" : "0",
  "charm" : "0",
  "coercion_career" : "0",
  "coercion" : "0",
  "computers_career" : "0",
  "computers" : "0",
  "cool_career" : "1",
  "cool" : "0",
  "coordination_career" : "0",
  "coordination" : "0",
  "deception_career" : "0",
  "deception" : "0",
  "discipline_career" : "1",
  "discipline" : "1",
  "leadership_career" : "0",
  "leadership" : "0",
  "mechanics_career" : "0",
  "mechanics" : "0",
  "medicine_career" : "1",
  "medicine" : "1",
  "negotiation_career" : "0",
  "negotiation" : "0",
  "perception_career" : "0",
  "perception" : "0",
  "piloting_planetary_career" : "0",
  "piloting_planetary" : "0",
  "piloting_space_career" : "0",
  "piloting_space" : "0",
  "resilience_career" : "1",
  "resilience" : "2",
  "skulduggery_career" : "0",
  "skulduggery" : "1",
  "stealth_career" : "0",
  "stealth" : "0",
  "streetwise_career" : "0",
  "streetwise" : "0",
  "survival_career" : "0",
  "survival" : "0",
  "vigilance_career" : "1",
  "vigilance" : "1",

  "brawl_career" : "1",
  "brawl" : "0",
  "gunnery_career" : "0",
  "gunnery" : "0",
  "lightsaber_career" : "0",
  "lightsaber" : "0",
  "melee_career" : "1",
  "melee" : "1",
  "ranged_light_career" : "0",
  "ranged_light" : "0",
  "ranged_heavy_career" : "0",
  "ranged_heavy" : "0",

  "core_worlds_career" : "0",
  "core_worlds" : "0",
  "education_career" : "0",
  "education" : "0",
  "lore_career" : "0",
  "lore" : "0",
  "outer_rim_career" : "0",
  "outer_rim" : "0",
  "underworld_career" : "0",
  "underworld" : "0",
  "xenology_career" : "0",
  "xenology" : "0",

  "custom1_name" : "",
  "custom1_career" : "0",
  "custom1" : "0",
  "custom2_name" : "",
  "custom2_career" : "0",
  "custom2" : "0",
  "custom3_name" : "",
  "custom3_career" : "0",
  "custom3" : "0",
  "custom4_name" : "",
  "custom4_career" : "0",
  "custom4" : "0",
  "custom5_name" : "",
  "custom5_career" : "0",
  "custom5" : "0",

  "weapon1_name" : "lightsaber",
  "weapon1_skill" : "lightsaber (brawn)",
  "weapon1_damage" : "+6",
  "weapon1_range" : "engaged",
  "weapon1_crit" : "2",
  "weapon1_special" : "sunder, breach",
  "weapon2_name" : "vibroknife",
  "weapon2_skill" : "melee (brawn)",
  "weapon2_damage" : "+1",
  "weapon2_range" : "engaged",
  "weapon2_crit" : "3",
  "weapon2_special" : "vicious",

  "motivation1_type" : "protect my crew",
  "motivation1_text" : "my team are my familiy. i can't let anyone hurt them!",
  "motivation2_type" : "",
  "motivation2_text" : "",

  "emotional_strength1" : "bravery",
  "emotional_strength2" : "",
  "emotional_weakness1" : "recklessness",
  "emotional_weakness2" : "",
  "conflict" : "0",
  "morality" : "65",

  "credits" : "65",
  "equipment1" : "",
  "equipment2" : "",
  "equipment3" : "",
  "equipment4" : "",
  "equipment5" : "",
  "equipment6" : "",
  "equipment7" : "",
  "equipment8" : "",
  "equipment9" : "",
  "equipment10" : "",

  "ability1_name" : "aquatic",
  "ability1_page" : "48",
  "ability1_summary" : "breathe underwater, bro",
  "ability2_name" : "",
  "ability2_page" : "",
  "ability2_summary" : "",
  "ability3_name" : "",
  "ability3_page" : "",
  "ability3_summary" : "",
  "ability4_name" : "",
  "ability4_page" : "",
  "ability4_summary" : "",
  "ability5_name" : "",
  "ability5_page" : "",
  "ability5_summary" : "",
  "ability6_name" : "",
  "ability6_page" : "",
  "ability6_summary" : "",
  "ability7_name" : "",
  "ability7_page" : "",
  "ability7_summary" : "",
  "ability8_name" : "",
  "ability8_page" : "",
  "ability8_summary" : "",
  "ability9_name" : "",
  "ability9_page" : "",
  "ability9_summary" : "",
  "ability10_name" : "",
  "ability10_page" : "",
  "ability10_summary" : "",
  "ability11_name" : "",
  "ability11_page" : "",
  "ability11_summary" : "",
  "ability12_name" : "",
  "ability12_page" : "",
  "ability12_summary" : "",

  "force_power1_name" : "Enahnce",
  "force_power1_description" : "roll a force dice and add force pips to the results of an athletics roll",
  "force_power2_name" : "",
  "force_power2_description" : "",
  "forcerating_w" : "1",

  "earned_xp" : "130",
  "unspent_xp" : "0",

  "player" : "<a href='https://www.obsidianportal.com/profile/Yithian'>Yithian</a>",
  "campaign" : "<a href='https://orphansofthelight.obsidianportal.com/'>Orphans of the Light</a>",

  "bio" : "Fyor Kast was pretty carefree as a padawan on Green Star. Sure, they were basically stranded and yeah, it was well past the time the Jedi Council should have sent a search party. Those things bothered Fyor, but living on Green Star was just so... if not fun, then interesting!",
};
